import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";

import {
  UserCheck,
  ThumbsUp,
  MessageSquare,
  HeartHandshake,
  Smile,
  Users,
  Image,
  ExternalLink,
} from "lucide-react";

export default function BehavioralFeedbackPage({ feedback, screenshots = [] }) {
  const [activeTab, setActiveTab] = useState("results");

  return (
    <div className="min-h-screen flex bg-background px-4">
      <div className="w-full max-w-4xl space-y-6 py-8">
        <h1 className="text-3xl font-bold mb-6 text-center">
          Behavioral Evaluation Results
        </h1>

        <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
          <TabsList className="grid w-full grid-cols-2 mb-6">
            <TabsTrigger value="results">Evaluation Results</TabsTrigger>
            <TabsTrigger value="screenshots">Interview Screenshots</TabsTrigger>
          </TabsList>

          <TabsContent value="results" className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>Candidate Behavioral Review</CardTitle>
              </CardHeader>
              <CardContent className="space-y-8">
                <ScoreCard score={feedback.overallScore} />

                <Section
                  title="Candidate Summary"
                  icon={<UserCheck className="text-primary h-5 w-5" />}
                >
                  <p className="text-muted-foreground">{feedback.summary}</p>
                </Section>

                <Section
                  title="Attribute Ratings"
                  icon={<Users className="text-primary h-5 w-5" />}
                >
                  <AttributeList rating={feedback.rating} />
                </Section>

                <Section
                  title="Concerns"
                  icon={<MessageSquare className="h-5 w-5 text-red-700 dark:text-destructive/80" />}
                >
                  <p className="text-red-700 dark:text-destructive/80">{feedback.redflag}</p>

                </Section>
              </CardContent>
            </Card>

            <RecommendationCard recommendation={feedback.recommendation} />
            <div className="text-xs text-muted-foreground text-center mt-6">
              Generated by TaleeX AI. While we strive for accuracy, we recommend reviewing the interview overview for clarity and context.
            </div>
          </TabsContent>

          <TabsContent value="screenshots">
            <Card>
              <CardHeader>
                <div className="flex items-center gap-2">
                  <Image className="text-primary h-5 w-5" />
                  <CardTitle>Interview Screenshots</CardTitle>
                </div>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground mb-6">
                  View screenshots taken during key moments of the interview.
                </p>

                <ul className="space-y-3">
                  {screenshots?.map((screenshot, index) => (
                    <li
                      key={index}
                      className="border border-gray-200 dark:border-gray-700 rounded-lg p-4 
               hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
                    >
                      <a
                        href={screenshot?.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex items-center justify-between text-blue-600 dark:text-blue-400 
                 hover:underline"
                      >
                        <span className="truncate">
                          View Screenshot #{index + 1}
                        </span>
                        <ExternalLink className="h-4 w-4 ml-2" />
                      </a>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
}

function Section({ title, icon, children }) {
  return (
    <div>
      <div className="flex items-center gap-2 mb-2">
        {icon}
        <h3 className="text-lg font-semibold">{title}</h3>
      </div>
      <Separator className="mb-4" />
      {children}
    </div>
  );
}

function AttributeList({ rating }) {
  const attributes = {
    communication: <MessageSquare className="h-4 w-4 text-muted-foreground" />,
    professionalism: (
      <HeartHandshake className="h-4 w-4 text-muted-foreground" />
    ),
    attitude: <Smile className="h-4 w-4 text-muted-foreground" />,
    culturalFit: <Users className="h-4 w-4 text-muted-foreground" />,
  };

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
      {Object.entries(rating).map(([key, value]) => (
        <div
          key={key}
          className="flex items-center justify-between border rounded-lg p-3"
        >
          <div className="flex items-center gap-2">
            {attributes[key]}
            <span className="capitalize">{key.replace(/([A-Z])/g, " $1")}</span>
          </div>
          <Badge className="bg-primary/10 text-primary">{value}/10</Badge>
        </div>
      ))}
    </div>
  );
}

function ScoreCard({ score }) {
  const num = parseFloat(score);
  const getColor = (val) => {
    if (val >= 8) return "text-green-600";
    if (val >= 6) return "text-amber-600";
    return "text-red-600";
  };

  const getProgressColor = (val) => {
    if (val >= 8) return "bg-green-600";
    if (val >= 6) return "bg-amber-600";
    return "bg-red-600";
  };

  const color = getColor(num);
  const progressColor = getProgressColor(num);

  return (
    <div className="flex flex-col md:flex-row items-center justify-between gap-4">
      <div className="flex items-center gap-3">
        <div className={`text-5xl font-bold ${color}`}>{score}</div>
        <div className="text-muted-foreground">
          <div className="text-sm uppercase font-semibold">Overall Score</div>
          <div className="text-xs">Behavioral compatibility</div>
        </div>
      </div>
      <div className="w-full md:w-2/3">
        <div className="flex justify-between text-xs mb-1">
          <span>Needs Work</span>
          <span>Excellent</span>
        </div>
        <Progress
          value={num * 10}
          className="h-3"
          indicatorClassName={progressColor}
        />
      </div>
    </div>
  );
}

function RecommendationCard({ recommendation }) {
  const isRecommended = recommendation.verdict === "Yes";

  return (
    <Card
      className={
        isRecommended
          ? "border-green-200 bg-green-50 dark:border-green-900 dark:bg-green-900/20"
          : "border-red-200 bg-red-50 dark:border-destructive/30 dark:bg-destructive/10"
      }
    >
      <CardHeader>
        <div className="flex items-center gap-2">
          {/* <ThumbsUp
            className={`h-5 w-5 ${isRecommended ? "text-green-600" : "text-red-600"
              }`}
          /> */}
          <CardTitle className="text-lg">Recommendation</CardTitle>
        </div>
      </CardHeader>
      <CardContent>
        <div className="flex items-center gap-3 mb-3">
          <h3
            className={`text-xl ${isRecommended
              ? "text-green-700 dark:text-gray-200 font-semibold"
              : "text-red-700 dark:text-gray-200"
              }`}
          >
            {isRecommended ? "" : "Verdict"}
            {isRecommended ? "Recommended for Hire" : ""}
          </h3>
          <Badge
            className={
              isRecommended
                ? "bg-green-200 text-green-800 dark:bg-green-800/30 dark:text-green-300"
                : "bg-red-200 text-red-800 dark:bg-red-700/30 dark:text-red-100"
            }
          >
            {recommendation.verdict}
          </Badge>
        </div>

        <Separator className={
          isRecommended
            ? "bg-green-200 dark:bg-green-100/10"
            : "bg-red-200 dark:bg-destructive/10"
        }
        />

        <div className="mt-3">
          <p
            className={
              isRecommended
                ? "text-green-800 dark:text-gray-200"
                : "text-red-800 dark:text-gray-300"
            }
          >            {recommendation.reasoning}
          </p>
        </div>
      </CardContent>
    </Card>
  );
}

// function Badge({ className, children }) {
//   return (
//     <div
//       className={`inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 ${className}`}
//     >
//       {children}
//     </div>
//   );
// }

function Progress({ value, className, indicatorClassName }) {
  return (
    <div
      className={`relative h-2 w-full overflow-hidden rounded-full bg-primary/10 ${className}`}
    >
      <div
        className={`h-full ${indicatorClassName}`}
        style={{ width: `${value}%` }}
      />
    </div>
  );
}
